/* -LICENSE-START-
** Copyright (c) 2009 Blackmagic Design
**
** Permission is hereby granted, free of charge, to any person or organization
** obtaining a copy of the software and accompanying documentation covered by
** this license (the "Software") to use, reproduce, display, distribute,
** execute, and transmit the Software, and to prepare derivative works of the
** Software, and to permit third-parties to whom the Software is furnished to
** do so, all subject to the following:
** 
** The copyright notices in the Software and this entire statement, including
** the above license grant, this restriction and the following disclaimer,
** must be included in all copies of the Software, in whole or in part, and
** all derivative works of the Software, unless such copies or derivative
** works are solely in the form of machine-executable object code generated by
** a source language processor.
** 
** THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
** IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
** FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
** SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
** FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
** ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
** DEALINGS IN THE SOFTWARE.
** -LICENSE-END-
*/
/* DeckLinkAPI.h */

#ifndef __DeckLink_API_h__
#define __DeckLink_API_h__

#include <CoreFoundation/CoreFoundation.h>
#include <CoreFoundation/CFPlugInCOM.h>
#include <stdint.h>


// Interface UUIDs
// ===============

// "74E936FC-CC28-4A67-81A0-1E94E52D4E69"
#define IID_IDeckLinkIterator				(REFIID){0x74,0xE9,0x36,0xFC,0xCC,0x28,0x4A,0x67,0x81,0xA0,0x1E,0x94,0xE5,0x2D,0x4E,0x69}

// "B28131B6-59AC-4857-B5AC-CD75D5883E2F"
#define IID_IDeckLinkDisplayModeIterator	(REFIID){0xB2,0x81,0x31,0xB6,0x59,0xAC,0x48,0x57,0xB5,0xAC,0xCD,0x75,0xD5,0x88,0x3E,0x2F}

// "AF0CD6D5-8376-435e-8433-54F9DD530AC3"
#define IID_IDeckLinkDisplayMode			(REFIID){0xAF,0x0C,0xD6,0xD5,0x83,0x76,0x43,0x5e,0x84,0x33,0x54,0xF9,0xDD,0x53,0x0A,0xC3}

// "62BFF75D-6569-4E55-8D4D-66AA03829ABC"
#define IID_IDeckLink						(REFIID){0x62,0xBF,0xF7,0x5D,0x65,0x69,0x4E,0x55,0x8D,0x4D,0x66,0xAA,0x03,0x82,0x9A,0xBC}

// "2B54EDEF-5B32-429F-BA11-BB990596EACD"
#define IID_IDeckLinkInput					(REFIID){0x2B,0x54,0xED,0xEF,0x5B,0x32,0x42,0x9F,0xBA,0x11,0xBB,0x99,0x05,0x96,0xEA,0xCD}

// "AE5B3E9B-4E1E-4535-B6E8-480FF52F6CE5"
#define IID_IDeckLinkOutput					(REFIID){0xAE,0x5B,0x3E,0x9B,0x4E,0x1E,0x45,0x35,0xB6,0xE8,0x48,0x0F,0xF5,0x2F,0x6C,0xE5}

// "333F3A10-8C2D-43CF-B79D-46560FEEA1CE"
#define IID_IDeckLinkVideoFrame				(REFIID){0x33,0x3F,0x3A,0x10,0x8C,0x2D,0x43,0xCF,0xB7,0x9D,0x46,0x56,0x0F,0xEE,0xA1,0xCE}

// "C8B41D95-8848-40EE-9B37-6E3417FB114B"
#define IID_IDeckLinkVideoInputFrame		(REFIID){0xC8,0xB4,0x1D,0x95,0x88,0x48,0x40,0xEE,0x9B,0x37,0x6E,0x34,0x17,0xFB,0x11,0x4B}

// "C86DE4F6-A29F-42E3-AB3A-1363E29F0788"
#define IID_IDeckLinkAudioInputPacket		(REFIID){0xC8,0x6D,0xE4,0xF6,0xA2,0x9F,0x42,0xE3,0xAB,0x3A,0x13,0x63,0xE2,0x9F,0x07,0x88}

// "B8EAD569-B764-47F0-A73F-AE40DF6CBF10"
#define IID_IDeckLinkConfiguration			(REFIID){0xB8,0xEA,0xD5,0x69,0xB7,0x64,0x47,0xF0,0xA7,0x3F,0xAE,0x40,0xDF,0x6C,0xBF,0x10}

// Callbacks

// "EBD01AFA-E4B0-49C6-A01D-EDB9D1B55FD9"
#define IID_IDeckLinkVideoOutputCallback	(REFIID){0xEB,0xD0,0x1A,0xFA,0xE4,0xB0,0x49,0xC6,0xA0,0x1D,0xED,0xB9,0xD1,0xB5,0x5F,0xD9}

// "403C681B-7F46-4A12-B993-2BB127084EE6"
#define IID_IDeckLinkAudioOutputCallback	(REFIID){0x40,0x3C,0x68,0x1B,0x7F,0x46,0x4A,0x12,0xB9,0x93,0x2B,0xB1,0x27,0x08,0x4E,0xE6}

// "7F94F328-5ED4-4E9F-9729-76A86BDC99CC"
#define IID_IDeckLinkInputCallback			(REFIID){0x7F,0x94,0xF3,0x28,0x5E,0xD4,0x4E,0x9F,0x97,0x29,0x76,0xA8,0x6B,0xDC,0x99,0xCC}

// "B36EB6E7-9D29-4AA8-92EF-843B87A289E8"
#define IID_IDeckLinkMemoryAllocator		(REFIID){0xB3,0x6E,0xB6,0xE7,0x9D,0x29,0x4A,0xA8,0x92,0xEF,0x84,0x3B,0x87,0xA2,0x89,0xE8}


typedef bool		BMDbool;


/* Video display modes supported for output/input */
typedef uint32_t	BMDDisplayMode;
enum {
	bmdModeNTSC				= 'ntsc',
	bmdModeNTSC2398			= 'nt23',
	bmdModePAL				= 'pal ',
	//
	bmdModeHD1080psf2398	= '23ps',
	bmdModeHD1080psf24		= '24ps',
	bmdModeHD1080i50		= 'Hi50',
	bmdModeHD1080i5994		= 'Hi59',
	//
	bmdModeHD720p50			= 'hp50',
	bmdModeHD720p5994		= 'hp59',
	bmdModeHD720p60			= 'hp60',
	//
	bmdMode2k2398			= '2k23',
	bmdMode2k24				= '2k24'
};


/* Video pixel formats supported for output/input */
typedef uint32_t	BMDPixelFormat;
enum {
	bmdFormat8BitYUV		= '2vuy',
	bmdFormat10BitYUV		= 'v210',
	bmdFormat8BitARGB		= 0x20,
	bmdFormat8BitBGRA		= 'BGRA',
	bmdFormat10BitRGB		= 'r210'
};

/* Display mode supported flags */
typedef uint32_t	BMDDisplayModeSupport;
enum {
	bmdDisplayModeNotSupported				= 0,
	bmdDisplayModeSupported,
	bmdDisplayModeSupportedWithConversion
};

/* Flags to influence how a video frame is displayed */
typedef uint32_t	BMDFrameFlags;
enum {
	bmdFrameFlagDefault				= 0,
	bmdFrameFlagFlipVertical		= 1 << 0,
	//
	// Flags that are valid only for frames returned through IDeckLinkInput
	bmdFrameHasNoInputSource		= 1 << 31
};

/* Flags applicable to video input */
typedef uint32_t	BMDVideoInputModeFlags;
enum {
	bmdVideoInputFlagDefault	= 0
};


/* Frame Completion Callback */

typedef uint32_t	BMDOutputFrameCompletionResult;
enum {
	bmdOutputFrameCompleted,
	bmdOutputFrameDisplayedLate,
	bmdOutputFrameDropped,
	bmdOutputFrameFlushed
};


/* Audio sample rates supported for output/input */
typedef uint32_t	BMDAudioSampleRate;
enum {
	bmdAudioSampleRate48kHz		= 48000
};


/* Audio sample sizes supported for output/input */
typedef uint32_t	BMDAudioSampleType;
enum {
	bmdAudioSampleType16bitInteger		= 16,
	bmdAudioSampleType32bitInteger		= 32
};


/* Frame time types  for scheduling */

typedef SInt64	BMDTimeValue;
typedef SInt64	BMDTimeScale;


#if defined(__cplusplus)

/* Forward Declarations */ 
class IDeckLinkIterator;
class IDeckLinkDisplayModeIterator;
class IDeckLinkDisplayMode;
class IDeckLink;
class IDeckLinkVideoFrame;
class IDeckLinkVideoInputFrame;
class IDeckLinkAudioInputPacket;


/*******************************************************************************************************************
 ************************************* Callback Interfaces (implemented by the caller) *****************************
 *******************************************************************************************************************/

class IDeckLinkVideoOutputCallback : public IUnknown
{
public:
	virtual HRESULT STDMETHODCALLTYPE	ScheduledFrameCompleted (IDeckLinkVideoFrame* completedFrame, BMDOutputFrameCompletionResult result) = 0;
};

class IDeckLinkInputCallback : public IUnknown
{
public:
	virtual HRESULT STDMETHODCALLTYPE	VideoInputFrameArrived (IDeckLinkVideoInputFrame* videoFrame, IDeckLinkAudioInputPacket* audioPacket) = 0;
};

class IDeckLinkMemoryAllocator : public IUnknown
{
public:
	virtual HRESULT STDMETHODCALLTYPE	AllocateBuffer (uint32_t bufferSize, void* *allocatedBuffer) = 0;
	virtual HRESULT STDMETHODCALLTYPE	ReleaseBuffer (void* buffer) = 0;
	
	virtual HRESULT STDMETHODCALLTYPE	Commit () = 0;
	virtual HRESULT STDMETHODCALLTYPE	Decommit () = 0;
};

class IDeckLinkAudioOutputCallback : public IUnknown
{
public:
	virtual HRESULT STDMETHODCALLTYPE	RenderAudioSamples (BMDbool preroll) = 0;
};


/*******************************************************************************************************************
 ************************************************ DeckLink Device Discovery ****************************************
 *******************************************************************************************************************/

class IDeckLinkIterator : public IUnknown
{
public:
	virtual HRESULT STDMETHODCALLTYPE	Next (IDeckLink* *deckLinkInstance) = 0;
};


class IDeckLinkDisplayModeIterator : public IUnknown
{
public:
	virtual	HRESULT	STDMETHODCALLTYPE	Next (IDeckLinkDisplayMode* *deckLinkDisplayMode) = 0;
};


class IDeckLinkDisplayMode : public IUnknown
{
public:
	virtual	HRESULT			STDMETHODCALLTYPE	GetName (CFStringRef* name) = 0;
	virtual	BMDDisplayMode	STDMETHODCALLTYPE	GetDisplayMode () = 0;
	virtual	long			STDMETHODCALLTYPE	GetWidth () = 0;
	virtual	long			STDMETHODCALLTYPE	GetHeight () = 0;
	virtual	HRESULT			STDMETHODCALLTYPE	GetFrameRate (BMDTimeValue *frameDuration, BMDTimeScale *timeScale) = 0;
};


class IDeckLink : public IUnknown
{
public:
	virtual HRESULT STDMETHODCALLTYPE	GetModelName (CFStringRef* modelName) = 0;
};


/*******************************************************************************************************************
 ***************************************************** DeckLink Video **********************************************
 *******************************************************************************************************************/

// IDeckLinkOutput.  Created by QueryInterface from IDeckLink.
class IDeckLinkOutput : public IUnknown
{
public:
	// Display mode predicates
	virtual	HRESULT	STDMETHODCALLTYPE	DoesSupportVideoMode (BMDDisplayMode displayMode, BMDPixelFormat pixelFormat, BMDDisplayModeSupport *result) = 0;
	virtual HRESULT	STDMETHODCALLTYPE	GetDisplayModeIterator (IDeckLinkDisplayModeIterator* *iterator) = 0;
	
	
	// Video output
	virtual HRESULT STDMETHODCALLTYPE	EnableVideoOutput (BMDDisplayMode displayMode) = 0;
	virtual HRESULT STDMETHODCALLTYPE	DisableVideoOutput () = 0;
	
	virtual HRESULT STDMETHODCALLTYPE	SetVideoOutputFrameMemoryAllocator (IDeckLinkMemoryAllocator* theAllocator) = 0;
	virtual HRESULT STDMETHODCALLTYPE	CreateVideoFrame (int32_t width, int32_t height, int32_t rowBytes, BMDPixelFormat pixelFormat, BMDFrameFlags flags, IDeckLinkVideoFrame* *outFrame) = 0;
	virtual HRESULT STDMETHODCALLTYPE	CreateVideoFrameFromBuffer (void* buffer, int32_t width, int32_t height, int32_t rowBytes, BMDPixelFormat pixelFormat, BMDFrameFlags flags, IDeckLinkVideoFrame* *outFrame) = 0;
	
	virtual HRESULT STDMETHODCALLTYPE	DisplayVideoFrameSync (IDeckLinkVideoFrame* theFrame) = 0;
	virtual HRESULT STDMETHODCALLTYPE	ScheduleVideoFrame (IDeckLinkVideoFrame* theFrame, BMDTimeValue displayTime, BMDTimeValue displayDuration, BMDTimeScale timeScale) = 0;
	virtual HRESULT STDMETHODCALLTYPE	SetScheduledFrameCompletionCallback (IDeckLinkVideoOutputCallback* theCallback) = 0;
	
	
	// Audio output
	virtual HRESULT STDMETHODCALLTYPE	EnableAudioOutput (BMDAudioSampleRate sampleRate, BMDAudioSampleType sampleType, uint32_t channelCount) = 0;
	virtual HRESULT STDMETHODCALLTYPE	DisableAudioOutput () = 0;
	
	virtual HRESULT STDMETHODCALLTYPE	WriteAudioSamplesSync (void* buffer, uint32_t sampleFrameCount, uint32_t *sampleFramesWritten) = 0;
	
	virtual HRESULT STDMETHODCALLTYPE	BeginAudioPreroll () = 0;
	virtual HRESULT STDMETHODCALLTYPE	EndAudioPreroll () = 0;
	virtual HRESULT STDMETHODCALLTYPE	ScheduleAudioSamples (void* buffer, uint32_t sampleFrameCount, BMDTimeValue streamTime, BMDTimeScale timeScale, uint32_t *sampleFramesWritten) = 0;
	
	virtual HRESULT STDMETHODCALLTYPE	GetBufferedAudioSampleFrameCount (uint32_t *bufferedSampleCount) = 0;
	virtual HRESULT STDMETHODCALLTYPE	FlushBufferedAudioSamples () = 0;
	
	virtual HRESULT STDMETHODCALLTYPE	SetAudioCallback (IDeckLinkAudioOutputCallback* theCallback) = 0;
	
	
	// Output control
	virtual HRESULT STDMETHODCALLTYPE	StartScheduledPlayback (BMDTimeValue playbackStartTime, BMDTimeScale timeScale, double playbackSpeed) = 0;
	virtual HRESULT STDMETHODCALLTYPE	StopScheduledPlayback (BMDTimeValue stopPlaybackAtTime, BMDTimeValue *actualStopTime, BMDTimeScale timeScale) = 0;
	virtual HRESULT STDMETHODCALLTYPE	GetHardwareReferenceClock (BMDTimeScale desiredTimeScale, BMDTimeValue *elapsedTimeSinceSchedulerBegan) = 0;
};


// IDeckLinkInput.  Created by QueryInterface from IDeckLink.
class IDeckLinkInput : public IUnknown
{
public:
	virtual	HRESULT	STDMETHODCALLTYPE	DoesSupportVideoMode (BMDDisplayMode displayMode, BMDPixelFormat pixelFormat, BMDDisplayModeSupport *result) = 0;
	virtual HRESULT	STDMETHODCALLTYPE	GetDisplayModeIterator (IDeckLinkDisplayModeIterator **iterator) = 0;
	
	// Video input
	virtual HRESULT STDMETHODCALLTYPE	EnableVideoInput (BMDDisplayMode displayMode, BMDPixelFormat pixelFormat, BMDVideoInputModeFlags flags) = 0;
	virtual HRESULT STDMETHODCALLTYPE	DisableVideoInput () = 0;
	
	// Audio input
	virtual HRESULT STDMETHODCALLTYPE	EnableAudioInput (BMDAudioSampleRate sampleRate, BMDAudioSampleType sampleType, uint32_t channelCount) = 0;
	virtual HRESULT STDMETHODCALLTYPE	DisableAudioInput () = 0;
	virtual HRESULT STDMETHODCALLTYPE	ReadAudioSamples (void* buffer, uint32_t sampleFrameCount, uint32_t *sampleFramesRead, BMDTimeValue *audioPacketTime, BMDTimeScale timeScale) = 0;
	virtual HRESULT STDMETHODCALLTYPE	GetBufferedAudioSampleFrameCount (uint32_t *bufferedSampleCount) = 0;
	
	// Input control
	virtual HRESULT	STDMETHODCALLTYPE	StartStreams () = 0;
	virtual HRESULT	STDMETHODCALLTYPE	StopStreams () = 0;
	virtual HRESULT	STDMETHODCALLTYPE	PauseStreams () = 0;
	virtual HRESULT STDMETHODCALLTYPE	SetCallback (IDeckLinkInputCallback* theCallback) = 0;
};


// IDeckLinkVideoFrame.  Created by IDeckLinkOutput::CreateVideoFrame.
class IDeckLinkVideoFrame : public IUnknown
{
public:
	virtual long STDMETHODCALLTYPE					GetWidth () = 0;
	virtual long STDMETHODCALLTYPE					GetHeight () = 0;
	virtual long STDMETHODCALLTYPE					GetRowBytes () = 0;
	virtual BMDPixelFormat STDMETHODCALLTYPE		GetPixelFormat () = 0;
	virtual BMDFrameFlags STDMETHODCALLTYPE			GetFlags () = 0;
	virtual HRESULT STDMETHODCALLTYPE				GetBytes (void* *buffer) = 0;
};


// IDeckLinkVideoInputFrame.  Provided by the IDeckLinkVideoInput frame arrival callback.
class IDeckLinkVideoInputFrame : public IDeckLinkVideoFrame
{
public:
	virtual HRESULT STDMETHODCALLTYPE			GetFrameTime (BMDTimeValue *frameTime, BMDTimeValue *frameDuration, BMDTimeScale timeScale) = 0;
};


/*******************************************************************************************************************
 ***************************************************** DeckLink Audio **********************************************
 *******************************************************************************************************************/

// IDeckLinkAudioInputPacket.  Provided by the IDeckLinkInput callback.
class IDeckLinkAudioInputPacket : public IUnknown
{
public:
	virtual long STDMETHODCALLTYPE					GetSampleCount () = 0;
	virtual HRESULT STDMETHODCALLTYPE				GetBytes (void* *buffer) = 0;
	
	virtual HRESULT STDMETHODCALLTYPE				GetAudioPacketTime (BMDTimeValue *packetTime, BMDTimeScale timeScale) = 0;
};


/*******************************************************************************************************************
 ************************************************* DeckLink Configuration ******************************************
 *******************************************************************************************************************/

typedef uint32_t	BMDVideoConnection;
enum {
	bmdVideoConnectionSDI		= 'sdi ',
	bmdVideoConnectionHDMI		= 'hdmi',
	bmdVideoConnectionComponent	= 'cpnt',
	bmdVideoConnectionComposite	= 'cmst',
	bmdVideoConnectionSVideo	= 'svid'
};

typedef uint32_t	BMDAnalogVideoFlags;
enum {
	bmdAnalogVideoFlagCompositeSetup75			= 1 << 0,
	bmdAnalogVideoFlagComponentBetacamLevels	= 1 << 1
};

typedef uint32_t	BMDAudioConnection;
enum {
	bmdAudioConnectionEmbedded	= 'embd',
	bmdAudioConnectionAESEBU	= 'aes ',
	bmdAudioConnectionAnalog	= 'anlg'
};

typedef uint32_t	BMDVideoOutputConversionMode;
enum {
	bmdNoVideoOutputConversion							= 'none',
	bmdVideoOutputLetterboxDownonversion				= 'ltbx',
	bmdVideoOutputAnamorphicDownonversion				= 'amph',
	bmdVideoOutputHD720toHD1080Conversion				= '720c',
	bmdVideoOutputHardwareLetterboxDownconversion		= 'HWlb',
	bmdVideoOutputHardwareAnamorphicDownconversion		= 'HWam',
	bmdVideoOutputHardwareCenterCutDownconversion		= 'HWcc'
};

typedef uint32_t	BMDVideoInputConversionMode;
enum {
	bmdNoVideoInputConversion							= 'none',
	bmdVideoInputLetterboxDownconversionFromHD1080		= '10lb',
	bmdVideoInputAnamorphicDownconversionFromHD1080		= '10am',
	bmdVideoInputLetterboxDownconversionFromHD720		= '72lb',
	bmdVideoInputAnamorphicDownconversionFromHD720		= '72am',
	bmdVideoInputLetterboxUpconversion					= 'lbup',
	bmdVideoInputAnamorphicUpconversion					= 'amup'
};


// IDeckLinkConfiguration.  Created by QueryInterface from IDeckLink.
class IDeckLinkConfiguration : public IUnknown
{
public:
	virtual HRESULT STDMETHODCALLTYPE	GetConfigurationValidator (IDeckLinkConfiguration** configObject) = 0;
	virtual HRESULT STDMETHODCALLTYPE	WriteConfigurationToPreferences () = 0;
	
	// Video output configuration
	virtual HRESULT STDMETHODCALLTYPE	SetVideoOutputFormat (BMDVideoConnection videoOutputConnection) = 0;
	virtual HRESULT STDMETHODCALLTYPE	IsVideoOutputActive (BMDVideoConnection videoOutputConnection, BMDbool *active) = 0;
	
	virtual HRESULT STDMETHODCALLTYPE	SetAnalogVideoOutputFlags (BMDAnalogVideoFlags analogVideoFlags) = 0;
	virtual HRESULT STDMETHODCALLTYPE	GetAnalogVideoOutputFlags (BMDAnalogVideoFlags *analogVideoFlags) = 0;
	
	virtual HRESULT STDMETHODCALLTYPE	EnableFieldFlickerRemovalWhenPaused (BMDbool enable) = 0;
	virtual HRESULT STDMETHODCALLTYPE	IsEnabledFieldFlickerRemovalWhenPaused (BMDbool *enabled) = 0;
	
	virtual HRESULT STDMETHODCALLTYPE	SetDualLinkVideoOutput (BMDbool enableDualLinkOutput, BMDbool enable3GbsOutput) = 0;
	virtual HRESULT STDMETHODCALLTYPE	GetDualLinkVideoOutput (BMDbool *dualLinkOutputEnabled, BMDbool *threeGbsOutputEnabled) = 0;
	
	virtual HRESULT STDMETHODCALLTYPE	SetVideoOutputConversionMode (BMDVideoOutputConversionMode conversionMode) = 0;
	virtual HRESULT STDMETHODCALLTYPE	GetVideoOutputConversionMode (BMDVideoOutputConversionMode *conversionMode) = 0;
	
	virtual HRESULT STDMETHODCALLTYPE	Set_HD1080p24_to_HD1080i5994_Conversion (BMDbool enable) = 0;
	virtual HRESULT STDMETHODCALLTYPE	Get_HD1080p24_to_HD1080i5994_Conversion (BMDbool *enabled) = 0;
	
	
	// Video input configuration
	virtual HRESULT STDMETHODCALLTYPE	SetVideoInputFormat (BMDVideoConnection videoInputFormat) = 0;
	virtual HRESULT STDMETHODCALLTYPE	GetVideoInputFormat (BMDVideoConnection *videoInputFormat) = 0;
	
	virtual HRESULT STDMETHODCALLTYPE	SetAnalogVideoInputFlags (BMDAnalogVideoFlags analogVideoFlags) = 0;
	virtual HRESULT STDMETHODCALLTYPE	GetAnalogVideoInputFlags (BMDAnalogVideoFlags *analogVideoFlags) = 0;
	
	virtual HRESULT STDMETHODCALLTYPE	SetVideoInputConversionMode (BMDVideoInputConversionMode conversionMode) = 0;
	virtual HRESULT STDMETHODCALLTYPE	GetVideoInputConversionMode (BMDVideoInputConversionMode *conversionMode) = 0;
	
	virtual HRESULT STDMETHODCALLTYPE	SetBlackVideoOutputDuringCapture (BMDbool blackOutInCapture) = 0;
	virtual HRESULT STDMETHODCALLTYPE	GetBlackVideoOutputDuringCapture (BMDbool *blackOutInCapture) = 0;
	
	virtual HRESULT STDMETHODCALLTYPE	Set32PulldownSequenceInitialTimecodeFrame (uint32_t aFrameTimecode) = 0;
	virtual HRESULT STDMETHODCALLTYPE	Get32PulldownSequenceInitialTimecodeFrame (uint32_t *aFrameTimecode) = 0;
	
	virtual HRESULT STDMETHODCALLTYPE	SetVancSourceLineMapping (uint32_t activeLine1VANCsource, uint32_t activeLine2VANCsource, uint32_t activeLine3VANCsource) = 0;
	virtual HRESULT STDMETHODCALLTYPE	GetVancSourceLineMapping (uint32_t *activeLine1VANCsource, uint32_t *activeLine2VANCsource, uint32_t *activeLine3VANCsource) = 0;
	
	
	// Audio input configuration
	virtual HRESULT STDMETHODCALLTYPE	SetAudioInputFormat (BMDAudioConnection audioInputFormat) = 0;
	virtual HRESULT STDMETHODCALLTYPE	GetAudioInputFormat (BMDAudioConnection *audioInputFormat) = 0;
};


extern "C" {
	// Function for create an IDeckLinkIterator instance
	IDeckLinkIterator*		CreateDeckLinkIteratorInstance (void);
};


#endif		// defined(__cplusplus)

#endif		// __DeckLink_API_h__

